*** Settings ***
Documentation    
Resource    ./capacity_market_unit_step_definitions.resource
Metadata    Feature    Capacity Market Unit
Metadata    Generated by    _gherkin2robotframework on 2025-04-03T15:27:40.823969_

*** Test Cases ***
Correct status code for valid request
    Given user has a connection to the api endpoint
    When user retrieves all capacity market units
    Then the status code is 200


